/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package revature;

import java.sql.Date;
import java.util.Scanner;

import revature.Controller.Controller;

public class App {

    static final Scanner sc = new Scanner(System.in);
    public static void main(String[] args) {
        // Date s=new Date(0);
        Controller con = new Controller();
    }
}
